import os
from google import genai


class Content:
    def generate_audio(prompt: str) -> str | None:
        return None
    def generate_video(prompt: str) -> str | None:
        return None
    def generate_story(prompt: str) -> str | None:
        """
        Returns the content (story) generated by Gemini or None if an error occurs.
        """
        try:
            api_key = os.getenv("GEMINI_API_KEY")
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model='gemini-2.0-flash-001', contents=prompt
            )
            return response.text
        except Exception as e:
            print(e)
            return None